version: "2"
networks:
  gamma:
services:
  kpi:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    networks:
      - default
      - gamma
    ports:
      - 8080:8080
    environment:
      OAUTH_INTERNAL_HOST: http://gamma-backend:8081/api
    volumes:
    - ./src:/usr/src/app/src
    - ./config:/usr/src/app/config
    - ./node_modules:/usr/src/app/node_modules
  gamma-frontend:
    image: cthit/gamma-frontend:development
    environment:
      HTTP_PROXY: http://gamma-backend:8081
    depends_on:
      - gamma-backend
    networks:
      - gamma
    ports:
      - 3000:3000
  gamma-backend:
    image: cthit/gamma-backend:development
    environment:
      # Default admin user name = admin
      # Default admin password  = password
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: gamma-db
      DB_PORT: 5432
      DB_NAME: postgres
      REDIS_HOST: gamma-redis
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379
      GOTIFY_KEY: "123abc"
      GOTIFY_URL: http://gamma-gotify:8080/mail
      DEFAULT_CLIENT_NAME: demo
      DEFAULT_CLIENT_ID: id
      DEFAULT_CLIENT_SECRET: secret
      DEFAULT_REDIRECT_URI: http://localhost:8080/auth/callback
      DEFAULT_API_KEY: key
      SERVER_PORT: 8081
      SUCCESSFUL_LOGIN: http://localhost:3000
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      BACKEND_URI: http://localhost:8081/api/
      ROOT_DEBUG_LEVEL: debug
      WEB_DEBUG_LEVEL: debug
      PRODUCTION: "false"
      COOKIE_DOMAIN: localhost
      IS_MOCKING_CLIENT: "true"
    depends_on:
      - gamma-redis
      - gamma-db
    networks:
      - gamma
    ports:
      - 8081:8081
  gamma-redis:
    image: redis:5.0
    networks:
      - gamma
  gamma-db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    networks:
      - gamma